### ISSUE TITLE
Warning in Logstash

### ISSUE THREAD

**Issue by Speedy1971** [DynamiteAI/dynamite-nsm#21]
Hi, there is a logstash warning and the data are not indexed in elaticsearch, the warning is:
[WARN ][logstash.filters.split   ] Only String and Array types are splittable. field:zeek is of type = NilClass
any suggestions?

**Comment by JaminB** [comment]
Hi @Speedy1971, likely an issue with one of the Zeek logs that we do not yet support. In all likelihood `conn.log` records are not getting dropped. We'll attempt to replicate and address.
