### ISSUE TITLE
Import pcap for analysis

### ISSUE THREAD

**Issue by qwe852** [DynamiteAI/dynamite-nsm#27]
Hi,

This tool is amazing. 
I'm wondering that is it possible to import Pcap files for analysis rather than deploy an agent?

**Comment by JaminB** [comment]
Hi @qwe852, we plan on adding a pcap ingestion mechanism by 0.8.0! Glad you found the tool useful.

**Comment by qwe852** [comment]
Got it. 

I'm looking forward to the new version!

Thanks.
