### ISSUE TITLE
always waiting for ElasticSearch API to become accessible

### ISSUE THREAD

**Issue by sucof** [DynamiteAI/dynamite-nsm#36]
Hi, there are a bug, when I install monitor, it always waiting for ElasticSearch API to become accessible, my OS is ubuntu18.04, and the memory is 8G.

**Comment by JaminB** [comment]
@sucof can you provide us with a copy of your /var/dynamite/dynamite-cluster.log

**Comment by sucof** [comment]
Very strange, it is not generate the /var/dynamite/elasticsearch/dynamite-cluster.log file, I user this command:dynamite install monitor

**Comment by JaminB** [comment]
I looks like installation possibly failed at some stage. 

You can always install the components separately.

```
dynamite install logstash
dynamite install elasticsearch
dynamite install kibana
```

Also, if you want to run these side-by-side increase your RAM to at least 12GB.

**Comment by sucof** [comment]
It's fine when I increase the RAM up to 16GB,thanks.
