### ISSUE TITLE
Missing high speed deployment examples + optimizations

### ISSUE THREAD

**Issue by gelim** [DynamiteAI/dynamite-nsm#42]
Hi,
I've read with interest https://github.com/DynamiteAI/dynamite-nsm/wiki/Agent-Deployment-Considerations and was wondering if you had succes stories to share related to agent install on 40Gb cards + any tweaks required on high speed hw in general. 

Thanks!

**Comment by JaminB** [comment]
Hi @gelim,

We are currently working with an end-user that has *close* to these requirements, at least during peak times. Lessons learned will be incorporated directly into the software as well as make it into this Wiki.

Dynamite-NSM is still in the early stages of development, and proper benchmarking is a big part of our roadmap. As a matter of fact, we plan on incorporating an inhouse benchmarking companion with our agent that will be able to report metrics like dropped packets, event throughput, and other relevant statistics.
