### ISSUE TITLE
logstash stop failed

### ISSUE THREAD

**Issue by daoxuans** [DynamiteAI/dynamite-nsm#62]
When i stop logstash, but the process is ruuning, i need to 'kill -9 _pid_'

root@earth:/home# dynamite logstash stop
2020-08-07 19:32:22 DYNAMITE_CMD    INFO       | LOG LEVEL: 20
2020-08-07 19:32:22 DYNAMITE_CMD    INFO       | LOG FILE: /var/log/dynamite/dynamite-07-08-2020.log
2020-08-07 19:32:22 LOGSTASH        INFO       | Attempting to stop LogStash [19124]
2020-08-07 19:32:22 LOGSTASH        ERROR      | An error occurred while attempting to stop LogStash.
{
 "PID": 19124,
 "RUNNING": **false**,
 "USER": "dynamite",
 "LOGS": "/var/log/dynamite/logstash/logstash-plain.log"
}
root@earth:/home# dynamite logstash status
2020-08-07 19:32:30 DYNAMITE_CMD    INFO       | LOG LEVEL: 20
2020-08-07 19:32:30 DYNAMITE_CMD    INFO       | LOG FILE: /var/log/dynamite/dynamite-07-08-2020.log
{
 "PID": 19124,
 "RUNNING": false,
 "USER": "dynamite",
 "LOGS": "/var/log/dynamite/logstash/logstash-plain.log"
}
root@earth:/home# **ps aux |grep logstash**
dynamite   19122  463 28.3 14824464 4654416 ?    Sl   19:30  10:30 /usr/lib/jvm/jdk-11.0.2//bin/java -cp /opt/dynamite/logstash/logstash-core/lib/jars/animal-sniffer-annotations-1.14.jar:/opt/dynamite/logstash/logstash-core/lib/jars/commons-codec-1.11.jar:/opt/dynamite/logstash/logstash-core/lib/jars/commons-compiler-3.0.11.jar:/opt/dynamite/logstash/logstash-core/lib/jars/error_prone_annotations-2.0.18.jar:/opt/dynamite/logstash/logstash-core/lib/jars/google-java-format-1.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/gradle-license-report-0.7.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/guava-22.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/j2objc-annotations-1.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jackson-annotations-2.9.8.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jackson-core-2.9.8.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jackson-databind-2.9.8.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jackson-dataformat-cbor-2.9.8.jar:/opt/dynamite/logstash/logstash-core/lib/jars/janino-3.0.11.jar:/opt/dynamite/logstash/logstash-core/lib/jars/javassist-3.24.0-GA.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jruby-complete-9.2.7.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/jsr305-1.3.9.jar:/opt/dynamite/logstash/logstash-core/lib/jars/log4j-api-2.11.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/log4j-core-2.11.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/log4j-slf4j-impl-2.11.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/logstash-core.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.commands-3.6.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.contenttype-3.4.100.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.expressions-3.4.300.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.filesystem-1.3.100.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.jobs-3.5.100.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.resources-3.7.100.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.core.runtime-3.7.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.equinox.app-1.3.100.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.equinox.common-3.6.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.equinox.preferences-3.4.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.equinox.registry-3.5.101.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.jdt.core-3.10.0.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.osgi-3.7.1.jar:/opt/dynamite/logstash/logstash-core/lib/jars/org.eclipse.text-3.5.101.jar:/opt/dynamite/logstash/logstash-core/lib/jars/slf4j-api-1.7.25.jar org.logstash.Logstash --path.settings=/etc/dynamite/logstash/
root       19484  0.0  0.0  17668   732 pts/2    S+   19:32   0:00 grep --color=auto logstash
root@earth:/home# kill -9 19122
root@earth:/home# ps aux |grep logstash
root       19486  0.0  0.0  17668  2880 pts/2    S+   19:32   0:00 grep --color=auto logstash

**Comment by JaminB** [comment]
This issue has been noted, and is being addressed by systemd migration in next release.
